# **Introduction to NumPy**

In [ ]:
import numpy as np

In [ ]:
#Declare Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) #matriks
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #tensor
c = np.array([1,2])
print("Matriks:")
print(a)
print("\n")
print("Tensor:")
print(b)
print(c)

Matriks:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Tensor:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[1 2]


In [ ]:
#ini untuk mencari tahu bentuk dari sebuah array/matriks/tensor
#mencari ordo berapa kali berapa dari sebuah matrisk atau tensor
c = np.shape(a) #ordo 3x3
d = np.shape(b) #ordo 3,2,2
print(c)
print(d)

(3, 3)
(3, 2, 2)


In [ ]:
#cara ke2 untuk mencari sebuah array dari sebuah matriks atau tensor
a.shape

(3, 3)

In [ ]:
#untuk mengambil elemen yang spesifik pada matriks(r,c)
print(a[0,1])
print(a[1,1])
print(a[1,2])

2
5
6


In [ ]:
#untuk mengambil elemen yang spesifik pada tensor(c,r)
print(b[1,1])
print(b[0,1])
print(b[2,1])
print(b[2,0])
print(b[2,0,0]) #indeks ke 0 pada kolom 2 row 0


[7 8]
[3 4]
[11 12]
[ 9 10]
9


In [ ]:
#Untuk Mengambil row pada matriks (r, :)
print(a[0,:])
print(a[1,:])
print("\n")
#untuk mengambil kolom pada matriks(:, c)
print(a[:,1])
print(a[:,2])

[1 2 3]
[4 5 6]


[2 5 8]
[3 6 9]


In [ ]:
#Untuk Mengambil row pada tensor (c, :)
print(b[0,:])
print(b[1,:])
print("\n")
#untuk mengambil kolom pada tensor(:, r)
print(b[:,0])
print(b[:,1])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
#Cara mengganti Value di 2-D Array
a[1,1] = 10
a[1,2] = 12
print(a)

[[ 1  2  3]
 [ 4 10 12]
 [ 7  8  9]]


In [ ]:
#Cara mengganti Value di tensor
b[1,1] = [13,14]
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [13 14]]

 [[ 9 10]
  [11 12]]]


# NumPy Array

## *1.NumPy Array*

In [ ]:
#Function untuk mendefinisikan nilai dalam array
#Single Dimensional Array
print(np.array([1,2,3,4,5,6,7,8])) #Vector
print('\n')

#Two-Dimensional Array
print(np.array([[1,2],[3,4],[5,6],[7,8]])) #Matriks
print('\n')

#Three-Dimensional Array (Tensor)
arred = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #Tensor
print(arred)
print("\n")
print(arred[1,1])
print(arred[1,1,0])
print("\n")
print(arred[2,0])
print(arred[2,1,1])
print("\n")
print(arred.shape)

[1 2 3 4 5 6 7 8]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[7 8]
7


[ 9 10]
12


(3, 2, 2)


In [ ]:
t = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #Tensor
#mengubah tensor menjadi matriks dan vektor
m= np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(m)
v= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(v)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## *2.NumPy Arange*

In [ ]:
#Function untuk mendefinisikan nilai-nilai yang berjarak sama dalam interval yang ditentukan dalam array
print(np.arange(8)) #Hanya Stop
print('\n')
print(np.arange(1,8)) #Start dan Stop
print('\n')
print(np.arange(1,18,3)) #Start, Stop, Step

[0 1 2 3 4 5 6 7]


[1 2 3 4 5 6 7]


[ 1  4  7 10 13 16]


## *3.NumPy zeros*

In [ ]:
#Function untuk menampilkan array baru degan ukuran tertentu dan berisi 0
#Default dtype adalah float
print(np.zeros(5))
print('\n')
print(np.zeros((5,5),dtype=int))
print('\n')
print(np.zeros((5,3),dtype=int))

[0. 0. 0. 0. 0.]


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## *4.NumPy ones*

In [ ]:
#Function untuk menampilkan array baru degan ukuran tertentu dan berisi 1
#Default dtype adalah float
print(np.ones(5))
print('\n')
print(np.ones((3,4), dtype=int))

[1. 1. 1. 1. 1.]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Manipulasi Array

## *1. Reshape*

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print('Array:')
print(a)
print('\n')

#Cara 1
print(np.reshape(a,(3,4))) #merubah menjadi ordo 4x3 dalam matriks
print('\n')
#Cara 2
b= a.reshape(3,4) #merubah menjadi ordo 3x4 dalam matriks
print(b)
print('\n')
c=a.reshape(3,2,2)
print(c)
print('\n')
d=a.reshape(2,2,3)
print(d)

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## *2. Flatten*

In [ ]:
#Array kembali menjadi bentuk Single-Dimensional(1-D) Array
c = np.array(b).flatten()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
d= np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(d)
print('\n')

#Cara 1
print(np.array(d).flatten()) 
print('\n')

#Cara 2
e = d.flatten()
print(e)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)
print('\n')
print(np.array(d).flatten()) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3 4 5 6 7 8 9]


## *3.Transpose*

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #tensor
print(b)
print('\n')
#cara 1
TransMat = np.array(b).transpose()
print(TransMat)
print('\n')
#cara 2
c = b.transpose()
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


In [ ]:
d = np.array([[1,2],[3,4],[5,6],[7,8]]) #matriks
print(d)
print('\n')
transd=np.array(d).transpose()
print(transd)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 3 5 7]
 [2 4 6 8]]


**Axis / Axes**


Digunakan untuk array yang lebih dari 1 Dimensi. Dalam 2-D array.

Axis 0 adalah sepanjang vertikal ke bawah melintasi baris (row).
Axis 1 adalah sepanjang horizontal ke samping melintasi kolom (column)

## *4.Concatenate*

In [ ]:
Arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr2 = np.array([[20,21,22],[23,24,25],[26,27,28]])
Arr3 = np.array([[11,15,16],[17,18,19],[30,31,32]])
#Ini Concatenate dalam Axis 0
print("Concatenate 2 Array dalam axis 0:") #nambahin di Baris/Row (vertical)
print(np.concatenate((Arr1,Arr2), axis = 0))

#Ini Concatenate dalam Axis 1
print("\nConcatenate 2 Array dalam axis 1:") #namabahin di Kolom/Column (horizontal)
print(np.concatenate((Arr1,Arr2), axis = 1))

Concatenate 2 Array dalam axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 21 22]
 [23 24 25]
 [26 27 28]]

Concatenate 2 Array dalam axis 1:
[[ 1  2  3 20 21 22]
 [ 4  5  6 23 24 25]
 [ 7  8  9 26 27 28]]


In [ ]:
Arr1 = np.array([[1,2],[4,5],[7,8]])
Arr2 = np.array([[20,21],[23,24],[26,27]])
print(np.concatenate((Arr1,Arr2), axis = 1))

[[ 1  2 20 21]
 [ 4  5 23 24]
 [ 7  8 26 27]]


In [ ]:
#Ini Concatenate dalam Axis 0
print("Concatenate 2 Array dalam axis 0:") #nambahin di Baris/Row (vertical)
print(np.concatenate((Arr1,Arr2,Arr3), axis = 0))

#Ini Concatenate dalam Axis 1
print("\nConcatenate 2 Array dalam axis 1:") #namabahin di Kolom/Column (horizontal)
print(np.concatenate((Arr1,Arr2,Arr3), axis = 1))

Concatenate 2 Array dalam axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [11 15 16]
 [17 18 19]
 [30 31 32]]

Concatenate 2 Array dalam axis 1:
[[ 1  2  3 20 21 22 11 15 16]
 [ 4  5  6 23 24 25 17 18 19]
 [ 7  8  9 26 27 28 30 31 32]]


In [ ]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(1,3)
print(x)
print(y)
print("\n")
z = np.concatenate((x,y[:,None]),axis=1)
print(z)

[[1 2 3]
 [4 5 6]]
[1 2]


[[1 2 3 1]
 [4 5 6 2]]


## *5.Stack*

In [ ]:
Arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr2 = np.array([[20,21,22],[23,24,25],[26,27,28]])

#Ini Stack dalam Axis -1
print("Stack 2 Array dalam axis -1:")
print(np.stack((Arr1,Arr2), axis = -1))

#Ini stack dalam Axis 0
print("\nStack 2 Array dalam axis 0:")
print(np.stack((Arr1,Arr2)))

#Ini stack dalam Axis 1
print("\nStack 2 Array dalam axis 1:")
print(np.stack((Arr1,Arr2), axis = 1))


Stack 2 Array dalam axis -1:
[[[ 1 20]
  [ 2 21]
  [ 3 22]]

 [[ 4 23]
  [ 5 24]
  [ 6 25]]

 [[ 7 26]
  [ 8 27]
  [ 9 28]]]

Stack 2 Array dalam axis 0:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]

Stack 2 Array dalam axis 1:
[[[ 1  2  3]
  [20 21 22]]

 [[ 4  5  6]
  [23 24 25]]

 [[ 7  8  9]
  [26 27 28]]]


## *6.Split*

In [ ]:
SplitArr = np.array([5,2,6,7,3,4,4,3,1])
#Membagi array menajdi 3 subarrays yang sama jumlah isinya:
SplitMat = np.split(SplitArr,3)
print(SplitMat)
print('\n')
#Membagi array di posisi yang di tunjuk sesuai dengan 1-D array:
SplitMat = np.split(SplitArr,[1,3,5]) #split di indeks 1, kemudian indeks 3 dan 5
print(SplitMat)
print('\n')
d=np.split(SplitArr,[2,4,3])
print(d)

[array([5, 2, 6]), array([7, 3, 4]), array([4, 3, 1])]


[array([5]), array([2, 6]), array([7, 3]), array([4, 4, 3, 1])]


[array([5, 2]), array([6, 7]), array([], dtype=int64), array([7, 3, 4, 4, 3, 1])]


## *7.Resize*

In [ ]:
#Mengubah size array, kalau size lebih besar maka terdapat salinan
ResizeArr = np.array([[1,2,3],[4,5,6]])

ResizeMat = np.resize(ResizeArr,(3,5))
print(ResizeMat)
print('\n')
d= np.resize(ResizeArr,(2,4))
print(d)

[[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 1 2 3]]


[[1 2 3 4]
 [5 6 1 2]]


## *8.Append*

In [ ]:
InitialAppend = np.array([[1,2,3],
                          [4,5,6]])

#Menggabungkan Array tanpa Axis (1-D array)
Append1 = np.append(InitialAppend, [7,8,9]) 
print(Append1)

#Menggabungkan Array dalam Axis 0 (2-D Array)
print('\n')
Append2 = np.append(InitialAppend, [[7,8,9]],
                    axis=0) 
print(Append2)

#Menggabungkan Array dalam Axis 1 (2-D Array)
print('\n')
Append3 = np.append(InitialAppend, [[7,8,9],[10,11,12]], axis=1) 
print(Append3)

[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## *9.Insert*

In [ ]:
InitialArr = np.array([[1,2],[3,4],[5,6]])
#Insert tanpa axis, maka array akan di flatten (1-D array)
Insert1 = np.insert(InitialArr,2,[11,12]) #Arr, Insert di indeks keberapa, yg mau di insert
print(Insert1)
# print('\n')

# print(InitialArr)

#Insert dalam axis = 0
print('\n')
Insert2 = np.insert(InitialArr,2,[11,12], axis = 0) 
print(Insert2)

#Insert dalam axis = 1
print('\n')
Insert3 = np.insert(InitialArr,2,[11,12,13], axis = 1) 
print(Insert3)


[ 1  2 11 12  3  4  5  6]


[[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]]


[[ 1  2 11]
 [ 3  4 12]
 [ 5  6 13]]


## *10.Delete*

In [ ]:
InitialDel = np.arange(1,9).reshape(2,4)
print(InitialDel)

#Delete tanpa axis, maka array akan di flatten (1-D array)
print('\n')
Delete1 = np.delete(InitialDel,2)  #delete indeks 2
print(Delete1)

#Delete dalam axis = 0, Row 2 Terhapus
print('\n')
Delete2 = np.delete(InitialDel,0, axis = 0) 
print(Delete2)

#Delete dalam axis = 1, Column 2 Terhapus
print('\n')
Delete3 = np.delete(InitialDel,1, axis = 1) 
print(Delete3)


[[1 2 3 4]
 [5 6 7 8]]


[1 2 4 5 6 7 8]


[[5 6 7 8]]


[[1 3 4]
 [5 7 8]]


## *11.Unique*

In [ ]:
InitialUnique = np.array([5,2,6,2,7,5,6,8,2,4,2,2])
print(InitialUnique)
print('\n')

#Value yang unik dari array:
UniqueFirst = np.unique(InitialUnique)
print('Value yang unik dari array:')
print(UniqueFirst)
print('\n')

#Value yang unik dari array dan mencari indeksnya dimana:
UniqueSecond = np.unique(InitialUnique, return_index=True)
print('Value yang unik dari array dan indeksnya:')
print(UniqueSecond)
print('\n')


#Ada berapa value unik dalam array:
UniqueSecond,indices = np.unique(InitialUnique, return_counts=True)
print('Ada berapa value unik dalam array:')
print(UniqueSecond)
print(indices)
print('\n')

#ct= np.split(InitialUnique,2)
ct= np.split(UniqueSecond,2)
print(ct)


[5 2 6 2 7 5 6 8 2 4 2 2]


Value yang unik dari array:
[2 4 5 6 7 8]


Value yang unik dari array dan indeksnya:
(array([2, 4, 5, 6, 7, 8]), array([1, 9, 0, 2, 4, 7]))


Ada berapa value unik dalam array:
[2 4 5 6 7 8]
[5 1 2 2 1 1]


[array([2, 4, 5]), array([6, 7, 8])]


## *12.Slice*

In [ ]:
InitialSlc = np.arange(10)
print(InitialSlc)
print('\n')

#Slicing satu elemen
s2 = InitialSlc[2]
print('Slicing satu elemen:')
print(s2)
print('\n')

#Slicing mulai dari indeks sekian.....
s3 = InitialSlc[3:]
print('Slicing mulai dari indeks sekian:')
print(s3)
print('\n')

#Slicing stop di indeks sekian.....
s31 = InitialSlc[:5]
print('Slicing stop di indeks sekian:')
print(s31)
print('\n')

#Slicing values diantara indeks- indeks
s4 = InitialSlc[3:8]
print('Slicing values diantara indeks- indeks:')
print(s4)
print('\n')

#Slicing values dengan step / interval sekian.....
s5 = InitialSlc[::2]
print('Slicing values dengan step / interval sekian:')
print(s5)
print('\n')

s = InitialSlc[2:7:2]
print('Slicing dengan semua parameter:')
print(s)


[0 1 2 3 4 5 6 7 8 9]


Slicing satu elemen:
2


Slicing mulai dari indeks sekian:
[3 4 5 6 7 8 9]


Slicing stop di indeks sekian:
[0 1 2 3 4]


Slicing values diantara indeks- indeks:
[3 4 5 6 7]


Slicing values dengan step / interval sekian:
[0 2 4 6 8]


Slicing dengan semua parameter:
[2 4 6]




In [ ]:
a = np.arange(25).reshape(5,5)
print(a)
print('\n')
print(a[1:4,0:3])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


[[ 5  6  7]
 [10 11 12]
 [15 16 17]]


# Experiment dengan Array

Mari membuat array dibawah ini <br>
[[1. 1. 1. 1. 1.]<br>
[1. 0. 0. 0. 1.]<br>
[1. 0. 9. 0. 1.]<br>
[1. 0. 0. 0. 1.]<br>
[1. 1. 1. 1. 1.]]

In [ ]:
out = np.ones((5,5))
print(out)
print("\n")
in_ = np.zeros((3,3))
print(in_)
in_[1,1] = 9 
print(in_)
print("\n")
#out[r:c]
out[1:4,1:4] = in_
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
